server:
    # E.g.: http://localhost:5000
    baseurl: CA_WEBCLIENT_HTTP_URL
    # E.g.: 0.0.0.0
    ip: CA_WEBCLIENT_BIND_IP_ADDRESS
    # E.g.: 5000
    port: CA_WEBCLIENT_SERVER_PORT

apiserver:
    # E.g.: localhost
    hostname: CA_API_SERVER_URL
    # E.g.: 8080
    port: CA_API_SERVER_PLAIN_PORT
    # E.g.: 8080
    publicport: CA_API_SERVER_PLAIN_PORT
    # E.g.: false
    tls: CA_API_SERVER_TLS_ENABLED

csr_defaults:
    # E.g.: SG
    country: COUNTRY_CODE
    # E.g.: Singapore
    state: STATE_NAME
    # E.g.: Singapore
    locality: LOCALITY_NAME
    # E.g.: Software NTU
    organization: ORGANIZATION_NAME
